### ISSUE TITLE
repo clones

### ISSUE THREAD

**Issue by nschloe** [dan-developer/dep-orthopy#2]
Hi Dan,

Thanks for your interest in my work! I noticed you're cloning some of my repositories as dep-* on your account. May I ask what didn't work for you in the original repos?

Cheers,
Nico

**Comment by dan-developer** [comment]
Hello. Hou are you?

I thank you for your contribution with the beautiful package.
The problem is not exactly in your repository but in another repository: https://github.com/sigma-py/quadpy

The versions you ask for earlier don't match the versions in your package. Nobody quite understands what happened yet. You can check this in the last 3 issues (as I am writing to you).

Thank you very much.

**Comment by nschloe** [comment]
I don't understand. What do you mean by _versions in your package_ and _another repository_? What _last 3 issues_?
